name: lokatrack
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  intl: ^0.19.0
  http: ^1.1.0  
  http_parser: ^4.0.2  # Added for multipart file uploads
  url_launcher: ^6.2.4
  image_picker: ^1.0.4  # Add this line  path: ^1.8.2
  path_provider: ^2.1.1  # Added for file path operations  image: ^4.1.3  # Added for image processing
  shared_preferences: ^2.2.2  # Added for token storage
  smooth_page_indicator: ^1.1.0  # Added for onboarding page indicator
  lottie: ^2.6.0  # Added for animations
  shimmer: ^3.0.0  # Add this line
  cached_network_image: ^3.3.0  # Add this line for better image caching control
  flutter_cache_manager: ^3.3.1  # Add this line for cache management
  mobile_scanner: ^5.0.1  # Modern QR code scanning library

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lokatrack_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/lokatrack_logo.png"
  adaptive_icon_padding: true
  adaptive_icon_foreground_scale_factor: 0.5 
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path_ios: "assets/images/lokatrack_logo.png"
  icon_size: 36 
  web:
    generate: true
    image_path: "assets/images/lokatrack_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/lokatrack_logo.png
    - assets/images/default_avatar.png
